#!/bin/bash
# ~/export_envs

#
# Export cross-system and local machine settings
#
# These should be settings which affect system-behaviors and utilities, but not
# settings like PATH or GLOBIGNORE which affect the behavior of invocations in
# bash itself
#


# APPDATA="/cygdrive/c/Users/`cmd.exe /c 'echo %USERNAME%'`/AppData/Roaming"
if ! [[ -d "$APPDATA" ]]; then
	unset APPDATA
else
	# USERPROFILE="/cygdrive/c/Users/`cmd.exe /c 'echo %USERNAME%'`"

	# PostgreSQL stuff:

	if [ -f "$APPDATA/postgresql/root.crt" ]; then
		export PGSSLROOTCERT="$APPDATA/postgresql/root.crt"
	else
		echo "$APPDATA/postgresql/root.crt" not found
	fi

	if [ -f "$APPDATA/postgresql/client.crt" ]; then
		export PGSSLCERT="$APPDATA/postgresql/client.crt"
	fi

	if [ -f "$APPDATA/postgresql/client.key" ]; then
		export PGSSLKEY="$APPDATA/postgresql/client.key"
	fi

fi

export EDITOR="vim"
export VISUAL="vim"
export HISTIGNORE="ls" # don't store plain ls-commands in bash history
export HISTFILESIZE=100000
#^ store up to the last 100,000 commands, truncating away the oldest ones on
# both login and logout
export HISTSIZE=10000
#^ store up to 10,000 commands for the current session, saving the most-recent
# ones **from the current session** up to that number on logout. Also, load this
# same number of past commands from the history-file on login for reuse in new
# sessions (but don't store the old ones on logout.)
export LS_COLORS="$LS_COLORS:fi=0;37:di=0;0:ln=1;36:ex=0;32:"
#^ default/grey directories, light-grey regular files, cyan symlinks, green
# executables
# http://linux-sxs.org/housekeeping/lscolors.html
# http://askubuntu.com/a/466203/432173

# configure `screen` to handle modifier-keys properly:
if [ "$TERM" == "screen" ]; then
	export TERM="xterm"
fi
