#!/bin/bash
# ~/export_local

# Variables and functions which are specific to the local machine go here.
# File should be sourced from ~/export_envs which should be sourced in .bashrc

# Examples:

function cdd {
	cd "/somewhere/commonly/visited/$1"
}

if [[ "$(uname -a)" = *Microsoft*GNU/Linux ]]; then
# if in a WSL shell (typically SUSE or Ubuntu):
	if ! [ "$(ls -A /d)" ]; then
	# if /d is not mounted yet:
		echo "About to mount D:\\ drive if available. ctrlC to cancel."
		sudo mkdir -p /d
		sudo mount -t drvfs D: /mnt/d \
			-o metadata,umask=0077,fmask=0177,uid=1000,gid=1000
		# ^ `-t` limits special file types. The rest assumes the current user
		# has ID 1000 and sets directories to u=rwx and files to u=rw, with
		# permissions to groups and world being denied.
	else
		echo "D:\\ appears to already be mounted. Carry on."
	fi
fi

