#!/usr/bin/env python

import sys
import codecs

try:
    # Python 2.6-2.7
    from HTMLParser import HTMLParser
except ImportError:
    # Python 3.x
    from html.parser import HTMLParser


target = sys.argv[1]

print(
    "Converting HTML-entities in {} to their original representations.".format(
        target
    )
)

with codecs.open(target,'r+', 'utf-8') as fh:
    s = fh.read()
    fh.seek(0)
    hp = HTMLParser()
    fh.write( hp.unescape(s) )
    fh.truncate()

# Code adapted from:
# https://stackoverflow.com/a/2087433/3159183
# https://stackoverflow.com/a/15976014/3159183

